# This is a basic workflow to help you get started with Actions

name: CI Start Stop

# Controls when the workflow will run

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Anypoint environment target'
        required: true
        type: choice
        options: [DEV, QAS, PRD]
      APP_NAME:
        description: 'Application name in Runtime Manager'
        required: true
      TARGET:
        description: 'Deployment target'
        required: true
        type: choice
        options: [EKS, CLOUDHUB]
      STATE:
        description: 'Start or Stop the application'
        required: true
        type: choice
        options: [START, STOP]
      REGION:
        description: 'Region of the API'
        required: true
        type: choice



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
